/*
 * Build step: derive the watch-side resource-ID enums from package.json.
 *
 * `pebble build` numbers resources by their position in `pebble.resources.media`
 * (1-based). The watchface loads PDCs with `new Poco.PebbleDrawCommandImage(id)`,
 * which throws a fatal "not found" if the id does not resolve to a PDC — so the
 * ids must never be hand-maintained. This script writes
 * src/embeddedjs/resource-ids.ts (gitignored) with `Casita` / `Icon` enums whose
 * values are the actual declaration positions, and fails the build if a required
 * resource is missing or isn't a `raw` (PDC) entry.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "src/embeddedjs/resource-ids.ts");

// enum member -> package.json media `name`
const CASITA = {
  Normal: "CASITA_NORMAL",
  Happy: "CASITA_HAPPY",
  Grinning: "CASITA_GRINNING",
  Sleeping: "CASITA_SLEEPING",
  Disconnected: "CASITA_DISCONNECTED",
  Sweating: "CASITA_SWEATING",
};
const ICON = {
  Thermometer: "ICON_THERMOMETER",
  ShoePrint: "ICON_SHOEPRINT",
  CalendarBlank: "ICON_CALENDARBLANK",
  BatteryLow: "ICON_BATTERY_LOW",
  BatteryMedium: "ICON_BATTERY_MEDIUM",
  BatteryHigh: "ICON_BATTERY_HIGH",
  HomeThermometer: "ICON_HOME_THERMOMETER",
};

interface MediaEntry {
  type: string;
  name: string;
  file: string;
}

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")) as {
  pebble: { resources: { media: MediaEntry[] } };
};
const media = pkg.pebble.resources.media;

function idOf(name: string): number {
  const index = media.findIndex((m) => m.name === name);
  if (index < 0) throw new Error(`package.json media: resource ${name} is not declared`);
  if (media[index].type !== "raw")
    throw new Error(`package.json media: ${name} must be type "raw" (PDC), got "${media[index].type}"`);
  return index + 1;
}

function renderEnum(name: string, members: Record<string, string>): string {
  const lines = Object.entries(members).map(([member, res]) => `  ${member} = ${idOf(res)}, // ${res}`);
  return `export enum ${name} {\n${lines.join("\n")}\n}\n`;
}

const out =
  `// GENERATED by tools/render-resources.ts from package.json \`pebble.resources.media\`.\n` +
  `// Do not edit — run \`bun run render-resources\`. Values are the 1-based declaration\n` +
  `// positions that \`pebble build\` assigns as resource IDs.\n\n` +
  renderEnum("Casita", CASITA) +
  "\n" +
  renderEnum("Icon", ICON);

writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${media.length} media entries)`);
